tutorial_e = {
    "footer": {
        "text": "Generated by NecroBot",
        "icon_url": "https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128",
    },
    "fields": [
        {
            "inline": False,
            "name": "The Permission System",
            "value": "The permissions system is the heart of NecroBot, it dictates what users can use which set of commands, however unlike other bots, it is not tied to a user's server permissions. This means that permissions must be manually assigned using the `perms` command. The server owner and users with administrator rights are automatically given level 5 and 4 accordingly but users needing permission level 3 and below will need manual assignment. When a user leaves a server their permission level is reset to 0, when a NecroBot Admin joins their level is automatically set to 6. All users with level 4 and above can use this commad but they can only set the permission level of other users to a number below their own.",
        },
        {
            "inline": False,
            "name": "Guild-Specific vs Discord-Wide Data",
            "value": "Profile data on necrobot is separated into two categories: data which depends on which server you call the command in (Server-Specific) and data which remains the same regardless of the server (Discord-Wide). Such things are money, badges and exp are discord wide and therefore are harder to obtain. Things like waifus, warnings and permissions are user server-specific data and therefore they can often be modified by a server's authorities. Other-server speccific data are things like the automoderation list, the starboard channel, ect... The thing to keep in mind is that server specific data can be edited by server authorities while discord-wide data can only be edited at the discretion of NecroBot admins.",
        },
        {
            "inline": False,
            "name": "Settings",
            "value": "The settings command is the command to customize how NecroBot behaves on your server. It includes a lot of subcommands which each cater to certain part so make sure to check out the help guide. In addition, several other commands allow you to decide how much NecroBot sees and does and how much users can use it. For example, the `disable` command allows to disable specific commands on the entire server, the `automod` command allows you to pick which channel/role/user is tracked by the bot automoderation and the `ignore` command allows you to pick who can and can't use the bot's features. Check out the Moderation and Server cogs for more info.",
        },
        {
            "inline": False,
            "name": "Feedback & Suggestions",
            "value": "Necro's always looking to improve his bot and has therefore created several ways to communicate feedback. You can join the official support server and drop your suggestion there (do `n!about` to get an invite link). You can also use the `report` command, just use it anywhere and add your message after the command, it'll be sent directly to the server. Finally, you can also contact Necro#6714 with your ideas. All spam/nsfw will be deleted and offenders will be blocked from the bot.",
        },
    ],
    "color": 161712,
    "type": "rich",
    "description": "A helpful tutorial section for a more advanced overview on NecroBot's system. This should give users a more indepth overview on certain specifics features of it. It's a lot of information to take in at once, so feel free to read it bit by bit, and if you have any more questions you can join the official support server. Use `n!about` for an invite link.",
    "title": "NecroBot Tutorial",
}
