gdpr_e = {
    "footer": {
        "text": "Generated by NecroBot",
        "icon_url": "https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128",
    },
    "fields": [
        {
            "inline": False,
            "name": "Your Data",
            "value": "From your personal data, and without ever using any command, the bot only stores your user ID which is technically discord's data but just as an FYI. Apart from that the bot will never store any sort of data that you don't give it through the use of command. So as long as you don't use any command the bot will only have access to your user id.",
        },
        {
            "inline": False,
            "name": "Your Messages",
            "value": "Commands you use will be logged into the bot purely for debugging and information purposes. These logs contain your user id and where you used the command in addition to the message itself and the time the command was used. If you do not wish for the bot to log these messages do not use commands. The bot can also, at the discretion of the server admins, send copies of any message you edit or delete as part of the automoderation aspect. These messages are not stored in the bot, they are merely forwarded to another channel chosen by the server authorities. If you do not wish for your deleted/edited messages to be logged you will have to take it up with the server authorities. By inviting the bot and using the command they give consent for all users present on the server to have their messages logged and by joining the server you give consent to obey its rules.",
        },
        {
            "inline": False,
            "name": "Your Server",
            "value": "The bot will generate a profile based on the server ID upon being invited to your server, in addition, as part of the automoderation initiative it will track and store the invites created by the server to help you track which invites user use when joining your server. If you do not wish for this to take place you must simply make sure you keep automoderation disabled. All other data the bot collects about your server will have to be given to it willingly through the use of commands.",
        },
        {
            "inline": False,
            "name": "Conclusion",
            "value": "The bottom line is, if you don't want the bot to log any of your data then you have to avoid using bot commands or being in a server which uses the bot's automoderation features. I can, at your request delete your user data but that user data will be instantly regenerated if you ever come in contact with the bot.",
        },
    ],
    "color": 161712,
    "type": "rich",
    "description": "This is information pertaining to you and the data the bot stores about you. I'm no lawyer so this is probably a shit legal explaination but I'm trying. I'm doing this bot as a hobby and am not getting any sort of financial compensation for it, this post is of informal nature rather than legal nature. Your data is split up in three categories: \n- **Your personal data** (which the bot does not store) \n- **Your Discord Data**: the data generated by discord for you to be able to use the service \n- **Your Bot Data**: the data generated by the bot for you to be able to use the bot. \nAs far as I'm aware GDPR only covers the first one unless you specifically requesting for an account termination, but read on nonethless.",
    "title": "Your Data and the Bot ",
}